### ISSUE TITLE
podenv --config ~/.config/podenv/gimp.dhall --list tosses error

### ISSUE THREAD

**Issue by jimccann-rh** [podenv/podenv#123]
If the parameter is at the end does not work as it puts it at the end for podman run instead of being used by podenv. 

podenv --config ~/.config/podenv/gimp.dhall --list
Unknown option --list
podenv: Received ExitFailure 1 when running
Raw command: podman run --rm --security-opt label=disable --network none --env DISPLAY=:0 --mount type=tmpfs,destination=/dev/shm --volume /tmp/.X11-unix:/tmp/.X11-unix --name gimp localhost/693902187a06c8cb35af244086bfdd6932ee0951fbe56a3476e40fd4b27141ca gimp --list

vs

[jimb0@fedora rheldev]$ podenv --list --config ~/.config/podenv/gimp.dhall
default: Application

**Comment by TristanCacqueray** [comment]
This should have been fixed by https://github.com/podenv/podenv/commit/479909ec46c830b698b47df831c7fd31751aec01 . Could you share the output of `podenv --version`?

**Comment by jimccann-rh** [comment]
podenv --version
0.1.0.0 222e906

**Comment by jimccann-rh** [comment]
FYI. I installed via https://copr.fedorainfracloud.org/coprs/petersen/podenv/

**Comment by TristanCacqueray** [comment]
I see thanks, the rpm is slightly outdated, the latest version is 0.2. You can try it using the binary release, see: https://github.com/podenv/podenv/blob/main/docs/tutorials/install.md#binary-installation

Though you are only missing a few minor fix, the command is basically the same between 0.1 and 0.2.

@juhp how can we bump the rpm?

**Comment by juhp** [comment]
Right it would be better to automate the copr build I suppose, but I can refresh it.

**Comment by juhp** [comment]
I have updated my above copr to 0.2.0 - thanks for the ping!
