### ISSUE TITLE
Idea of improvement with home stanza and selinux label

### ISSUE THREAD

**Issue by morucci** [podenv/podenv#2]
Hi,

Could it be possible to update the warning message:
➜  ~ ~fabien/.local/bin/podenv shell
SELinux is disabled because /home/fabien/.config/podenv-home doesn't have the container_file_t label.
By giving the command to set the label: 
chcon -Rt container_file_t .config/podenv-home

Thanks

**Comment by TristanCacqueray** [comment]
That sounds like a nice addition, could you make a PR to https://github.com/podenv/podenv/blob/9bf5a71b5697fa72ffa56b39cfb6a371a42d2db2/podenv/env.py#L425 please?
