### ISSUE TITLE
initial impressions

### ISSUE THREAD

**Issue by juhp** [podenv/podenv#25]
Thanks for this interesting project.

So I built podenv using LTS 18 and got it running in a VM.
The initial `podenv --list` seems to take quite some time:
```ShellSession
$ podenv --list
Initializing /home/petersen/.config/podenv/Hub.dhall

```
The first times I thought it was hanging or there was some timeout,
but finally it outputs a long list of Apps. (It might be good to add
a message "This may take some time" if this is expected.)

I got `docs/tutorials/create.md` to work okay (I just used vi instead of gimp).

But `podenv vi` fails for me:
```ShellSession
$ podenv vi
podenv: vi: not found
CallStack (from HasCallStack):
  error, called at src/Relude/Debug.hs:218:11 in relude-0.7.0.0-FtIHw33t24H7i0K6Sc8qVf:Relude.Debug
  error, called at src/Podenv/Config.hs:153:28 in podenv-0.1.0.0-8uaivfntuKMDUYHGXQZDiT:Podenv.Config
```
It seems I need to add my vi app to the list of apps.
How about adding an explicit example of how to add the gimp application to the list of known applications?
Anyway I see I really need to learn dhall properly now to make proper use of podenv!

It would nice to have a "create app" wizard or something for this. :-)

**Comment by TristanCacqueray** [comment]
Thank you so much for the feedback @juhp ! There is now #26 and https://github.com/podenv/hub/pull/29 that should help with the issues you reported.

Something that could be done in the futur is to automatically load applications defined in `~/.config/podenv/local.d` or something, then we wouldn't have to fiddle with the main config.

**Comment by juhp** [comment]
> Thank you so much for the feedback @juhp ! There is now #26 and [podenv/hub#29](https://github.com/podenv/hub/pull/29) that should help with the issues you reported.

Great thanks!

> Something that could be done in the future is to automatically load applications defined in `~/.config/podenv/local.d` or something, then we wouldn't have to fiddle with the main config.

That would be pretty awesome and convenient yes :+1: 
Okay I will open an rfe as a reminder.
