### ISSUE TITLE
RFE: support directly loading an app defined in ~/.config/podenv/local.d

### ISSUE THREAD

**Issue by juhp** [podenv/podenv#31]
From #25 the idea came up of being able to load apps without having to add then directly to the main application list.
For example for app configs that might live in `~/.config/podenv/local.d`.

**Comment by juhp** [comment]
I tested this now and seems working great, thanks a lot!
```ShellSession
$ cat ~/.config/podenv/local.d/toolbox.dhall
(env:PODENV).Application::{
, name = "toolbox"
, description = Some "A simple toolbox"
, runtime = (env:PODENV).Image "fedora:latest"
, capabilities = (env:PODENV).Capabilities::{
  , terminal = True
  , interactive = True
  , network = True
  , keep = True
  }
, command = [ "bash" ]
}
$ podenv toolbox 
toolbox
[root@localhost /]# 
```

**Comment by TristanCacqueray** [comment]
excellent, that's good to know. Also note that with #44 , this can be written as:

```dhall
{
, name = "toolbox"
, description = Some "A simple toolbox"
, runtime.image = "fedora:latest"
, capabilities = {
  , terminal = True
  , interactive = True
  , network = True
  , keep = True
  }
, command = [ "bash" ]
}
```

**Comment by juhp** [comment]
I tried that now but it doesn't seem to parse completely for me.

dhall-mode.el reformats `runtime = { image = "fedora:latest" }`
to `runtime.image = "fedora:latest"` but gives a different dhall errors.

**Comment by juhp** [comment]
Ah wait, doh, it is not merged yet!  Okay looking forward to this!!
