### ISSUE TITLE
Handle configured container status

### ISSUE THREAD

**Issue by TristanCacqueray** [podenv/podenv#48]
After a reboot, it seems like previously running container are set to the *configured* status, resulting in a podenv error: `Unknown container status: "configured"`.

I think we can simply treat this status as `stopped`.

**Comment by juhp** [comment]
It [seems](https://github.com/containers/podman/blob/main/libpod/define/containerstate.go#L42) there are more states, but they may not all need to be handled commonly?

**Comment by TristanCacqueray** [comment]
It's a bit tricky because when an application is using `keep`, then we need to handle some of the state differently.

Previous implementation of podenv would error when the desired container was found, letting the user deal with the left-over...

**Comment by TristanCacqueray** [comment]
In particular, I'm not sure what should be done for `configured`, `created`, `paused`, `stopped`. Though in #53 I improved the logic for the non `keep` case, and added support to handle those extra state.
