### ISSUE TITLE
passing arguments to podenv apps on the command line?

### ISSUE THREAD

**Issue by juhp** [podenv/podenv#56]
This is more a higher level question perhaps, but I was pondering if it would be possible to
somehow handle passing in non-file arguments to podenv apps from the commandline?

Say I wanted something like `podenv fedoraver 33` say (or `podenv "fedoraver 33"`)
to start a fedora:33 app/container for example. Well that are surely other possible ways to handle it.. (maybe an option?)
but could such "functions" be possible? Or is it better just to use a wrapper for this?
Any thoughts around such ideas? The main obstacle is probably typing?

Conversely it ought to be pretty easy to churn out such podenv apps with dhall I suppose,
but I was kind of dreaming that one could have pseudocode like this `\ ver -> { ..., runtime.image = "fedora:$ver" }`...
but that might be unrealistic or perhaps there is a better way.

**Comment by TristanCacqueray** [comment]
Glad you ask, podenv already knows how to decode Dhall function! You can try running `podenv --config '\(ver : Text) -> { runtime.image = "fedora:${ver}" }' --show 34`

Or if you put that config in `~/.config/podenv/local.d/myfedora.dhall`, you should see in `podenv --list`:

```
myfedora : λ ver → Application
```

... which can be used like so `podenv myfedora 35`

**Comment by juhp** [comment]
How about optional arguments is that possible too?

**Comment by TristanCacqueray** [comment]
You are welcome, I've opened a new issue for optional argument, thanks for the suggestion.
