### ISSUE TITLE
Improve CLI parser

### ISSUE THREAD

**Issue by TristanCacqueray** [podenv/podenv#60]
Currently, podenv will pass any remaining command line argument to the container command. Then to pass argument starting with a `-`, the user needs to use the `--` separator.

This isn't ideal, and it's going to be even more confusing with #59 . Perhaps this can be improved by:

- Enforce the use of `--` for passing extra container command argument
- Use a new `--arg` cli flag to pass argument, e.g. `podenv shell --arg=ls --arg=-la`

**Comment by TristanCacqueray** [comment]
In #62 I added a filter to handle podenv optparse until the app selector so that we don't need to use `--`.

**Comment by juhp** [comment]
Thanks for this

I guess the one downside of dropping optparse-applicative, is losing easy bash-completion support.
But maybe there is another way to generate it from `podenv --help`? (Actually it partially "half-works" already:
my copr builds still include the empty bash-completion support).
