### ISSUE TITLE
--home usage

### ISSUE THREAD

**Issue by juhp** [podenv/podenv#77]
I am not completely clear on how to use `--home`.

For example:
```shellsession
$ podenv --home ~ shell
podenv: Need app home
CallStack (from HasCallStack):
  error, called at src/Relude/Debug.hs:218:11 in relude-0.7.0.0-yjmQ8ULj3qKu1kTfacGaN:Relude.Debug
  error, called at src/Podenv/Application.hs:327:28 in podenv-0.1.0.0-inplace:Podenv.Application
```

I _think_ it sets the base directory for the application? And I know `home` is only defined for some apps.
Does it make sense to allow setting it for any app container?

I was actually trying to see if I could generalize `setRunAs` (in Application.hs) to not hardcode `/home`.

**Comment by TristanCacqueray** [comment]
You mean `--home $x` would be equivalent to `--volume ~/:$x` ? Then I think it's better to avoid such shortcut to keep the CLI as simple as possible.
Perhaps we could add a short version so that `-v ~/:$x` would be even shorter than when using `--home` :)

**Comment by juhp** [comment]
Ya, I think it is fine to drop `--home` for now - we could revisit the idea later perhaps if it seems useful.

**Comment by TristanCacqueray** [comment]
Alright, so `--home` is now removed, and we could add it back if needed.
