### ISSUE TITLE
Fix bash-completion support

### ISSUE THREAD

**Issue by TristanCacqueray** [podenv/podenv#79]
According to https://github.com/podenv/podenv/issues/60#issuecomment-946419580 , #62 broke bash-completion. 

We are still using optparse-applicative, but without the complete args, so perhaps we can fix the args handling to pass in https://github.com/podenv/podenv/blob/d0f8b2731ab389b5b252b76f199c223620f2d90e/src/Podenv/Main.hs#L70-L81 

It seems like we need to keep any toggle starting with `--bash-completion-`

**Comment by juhp** [comment]
Sorry I am not sure now - this might be my confusion actually.  Seems like it is working I think.
I didn't realise optparse-applicative was still there.

The reason I got confused is that:
```bashsession
$ podenv --[TAB]
$ podenv -[TAB]
--alsa            --kvm             --no-kvm          --shell
--config          --list            --no-network      --show
--cwd             --list-caps       --no-pipewire     --ssh
--dbus            --name            --no-pulseaudio   --terminal
--dhall-env       --namespace       --no-root         --tun
--dri             --network         --no-ssh          --update
--env             --no-alsa         --no-terminal     --verbose
--gpg             --no-cwd          --no-tun          --version
-h                --no-dbus         --no-video        --video
--help            --no-dri          --no-wayland      --volume
--home            --no-gpg          --no-x11          --wayland
--hostfile        --no-hostfile     --pipewire        --x11
--interactive     --no-interactive  --pulseaudio      
--keep            --no-keep         --root            
$ podenv -
```
but maybe that is the expected behavior (or bash-competion changed?).

Anyway this is probably notabug.

**Comment by juhp** [comment]
Actually this does seem different for podenv, though not such a big deal.
